// <auto-generated />
using System;
using ApiGastronomia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiGastronomia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612114619_RemoveRolSeeds")]
    partial class RemoveRolSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("MontoApertura")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_apertura");

                    b.Property<decimal?>("MontoCierreReal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_cierre_real");

                    b.Property<decimal?>("MontoCierreTeorico")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_cierre_teorico");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_apertura_id");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_cierre_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("cajas");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("LatitudPartida")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud_partida");

                    b.Property<double?>("LongitudPartida")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud_partida");

                    b.Property<int?>("MetodoPagoDefaultId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_default_id");

                    b.Property<string>("NombreGastronomico")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombreGastronomico");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoDefaultId");

                    b.ToTable("configuracion");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Demora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DemoraMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("demora");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("demoras");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision")
                        .HasColumnName("precio");

                    b.HasKey("PedidoId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.EstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "EnPreparacion"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ListoParaRetirar"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "EnCamino"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Retirado"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("metodo_pago");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.MetodoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("metodo_venta");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CajaId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cliente_direccion");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cliente_nombre");

                    b.Property<int?>("DemoraAprox")
                        .HasColumnType("integer")
                        .HasColumnName("demora_aprox");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaAsignado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignado");

                    b.Property<DateTime?>("FechaEnCamino")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_en_camino");

                    b.Property<DateTime?>("FechaEstimadoFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_estimado_fin");

                    b.Property<DateTime?>("FechaFinalizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<double?>("LatitudDestino")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud_destino");

                    b.Property<double?>("LongitudDestino")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud_destino");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_id");

                    b.Property<int>("MetodoVentaId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_venta_id");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer")
                        .HasColumnName("repartidor_id");

                    b.Property<double>("TotalEstimado")
                        .HasColumnType("double precision")
                        .HasColumnName("total_estimado");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("MetodoVentaId");

                    b.HasIndex("RepartidorId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("Demora")
                        .HasColumnType("integer")
                        .HasColumnName("demora");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioNombre")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Caja", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.Usuario", "UsuarioApertura")
                        .WithMany("CajasApertura")
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.Usuario", "UsuarioCierre")
                        .WithMany("CajasCierre")
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Configuracion", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.MetodoVenta", "MetodoPagoDefault")
                        .WithMany()
                        .HasForeignKey("MetodoPagoDefaultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MetodoPagoDefault");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Demora", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Demoras")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Demoras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.Caja", "Caja")
                        .WithMany("Pedidos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiGastronomia.Domain.Entities.EstadoPedido", "Estado")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.MetodoVenta", "MetodoVenta")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiGastronomia.Domain.Entities.Usuario", "Repartidor")
                        .WithMany("PedidosAsignados")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Caja");

                    b.Navigation("Estado");

                    b.Navigation("MetodoPago");

                    b.Navigation("MetodoVenta");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ApiGastronomia.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Caja", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.MetodoVenta", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Demoras");

                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiGastronomia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CajasApertura");

                    b.Navigation("CajasCierre");

                    b.Navigation("Demoras");

                    b.Navigation("PedidosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
